server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice # user服务的服务名称
#  zipkin:
#    base-url: http://localhost:9411
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: HZ

#opentracing:
#  jaeger:
#    enabled: true
#    udp-sender:
#      host: localhost
#      port: 6831
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
# 增加 Feign 超时时间，单位为毫秒
feign:
  client:
    config:
      default:
        readTimeout: 5000

logging:
  level:
    cn.itcast: info
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka